import type {
  MemoryRecord,
  PinnedMemory,
  Routine,
} from "./types";

export const dayBoundary = "04:00";

export const initialRoutines: Routine[] = [
  {
    id: "routine-1",
    routineId: "routine-definition-1",
    title: "Morning medication",
    description: "Take the morning medication after breakfast.",
    scheduledTime: "08:00",
    status: "completed",
    reminderState: "idle",
    streakText: "18 day streak",
  },
  {
    id: "routine-2",
    routineId: "routine-definition-2",
    title: "Lunch walk",
    description: "Walk outside for a short reset around lunch.",
    scheduledTime: "12:20",
    status: "pending",
    reminderState: "reminding",
    streakText: "4 day streak",
  },
  {
    id: "routine-3",
    routineId: "routine-definition-3",
    title: "Inbox zero pass",
    description: "Do one pass over urgent messages.",
    scheduledTime: "15:30",
    status: "pending",
    reminderState: "idle",
    streakText: "Due today",
  },
  {
    id: "routine-4",
    routineId: "routine-definition-4",
    title: "Evening shutdown",
    description: "Close work tabs and write the next first action.",
    scheduledTime: "22:45",
    status: "pending",
    reminderState: "idle",
    streakText: "Flexible window",
  },
];

export const initialPinnedMemories: PinnedMemory[] = [
  {
    id: "memory-1",
    memoryId: "memory-1",
    category: "Cuisine",
    title: "Handmade Shin Ramyun",
    description: "Soft egg, green onion, and a small cheese slice at home.",
    meta: "Pinned 2 days ago",
    position: 1,
    status: "active",
  },
  {
    id: "memory-2",
    memoryId: "memory-2",
    category: "Cuisine",
    title: "Corner Dumpling House",
    description: "Pan-fried pork dumplings with a quiet late lunch window.",
    meta: "Last done 18 days ago",
    position: 2,
    status: "active",
  },
  {
    id: "memory-3",
    memoryId: "memory-3",
    category: "Sightseeing",
    title: "Harbour sunset walk",
    description: "Short waterside route with a clear view after dinner.",
    meta: "Pinned yesterday",
    position: 1,
    status: "active",
  },
  {
    id: "memory-4",
    memoryId: "memory-4",
    category: "Sightseeing",
    title: "Museum sketch corner",
    description: "Slow visit, one exhibit, then ten minutes of notes.",
    meta: "Last done 41 days ago",
    position: 2,
    status: "active",
  },
];

export const memoryReplacementPool: PinnedMemory[] = [
  {
    id: "memory-5",
    memoryId: "memory-5",
    category: "Cuisine",
    title: "Bakery melon pan",
    description: "Buy one fresh pastry and sit near the window for tea.",
    meta: "Suggested from Cuisine",
    position: 3,
    status: "active",
  },
  {
    id: "memory-6",
    memoryId: "memory-6",
    category: "Cuisine",
    title: "Cold soba lunch",
    description: "Simple noodles, dipping sauce, and cucumber on a warm day.",
    meta: "Last done 24 days ago",
    position: 4,
    status: "active",
  },
  {
    id: "memory-7",
    memoryId: "memory-7",
    category: "Sightseeing",
    title: "Botanic garden loop",
    description: "One gentle loop, fern house, and a bench break.",
    meta: "Suggested from Sightseeing",
    position: 3,
    status: "active",
  },
  {
    id: "memory-8",
    memoryId: "memory-8",
    category: "Sightseeing",
    title: "Bookshop lane",
    description: "Browse one shelf, pick a postcard, and leave before crowded.",
    meta: "Last done 33 days ago",
    position: 4,
    status: "active",
  },
];

export const memoryRecords: MemoryRecord[] = [
  {
    id: "memory-1",
    categoryId: "category-cuisine",
    category: "Cuisine",
    title: "Handmade Shin Ramyun",
    description: "Soft egg, green onion, and a small cheese slice at home.",
    lastDoneText: "Last done 6 days ago",
    doneCount: 12,
    pinned: true,
  },
  {
    id: "memory-2",
    categoryId: "category-cuisine",
    category: "Cuisine",
    title: "Corner Dumpling House",
    description: "Pan-fried pork dumplings with a quiet late lunch window.",
    lastDoneText: "Last done 18 days ago",
    doneCount: 4,
    pinned: true,
  },
  {
    id: "memory-5",
    categoryId: "category-cuisine",
    category: "Cuisine",
    title: "Bakery melon pan",
    description: "Buy one fresh pastry and sit near the window for tea.",
    lastDoneText: "Never done",
    doneCount: 0,
    pinned: false,
  },
  {
    id: "memory-6",
    categoryId: "category-cuisine",
    category: "Cuisine",
    title: "Cold soba lunch",
    description: "Simple noodles, dipping sauce, and cucumber on a warm day.",
    lastDoneText: "Last done 24 days ago",
    doneCount: 3,
    pinned: false,
  },
  {
    id: "memory-3",
    categoryId: "category-sightseeing",
    category: "Sightseeing",
    title: "Harbour sunset walk",
    description: "Short waterside route with a clear view after dinner.",
    lastDoneText: "Last done 9 days ago",
    doneCount: 7,
    pinned: true,
  },
  {
    id: "memory-4",
    categoryId: "category-sightseeing",
    category: "Sightseeing",
    title: "Museum sketch corner",
    description: "Slow visit, one exhibit, then ten minutes of notes.",
    lastDoneText: "Last done 41 days ago",
    doneCount: 2,
    pinned: true,
  },
  {
    id: "memory-7",
    categoryId: "category-sightseeing",
    category: "Sightseeing",
    title: "Botanic garden loop",
    description: "One gentle loop, fern house, and a bench break.",
    lastDoneText: "Never done",
    doneCount: 0,
    pinned: false,
  },
  {
    id: "memory-8",
    categoryId: "category-sightseeing",
    category: "Sightseeing",
    title: "Bookshop lane",
    description: "Browse one shelf, pick a postcard, and leave before crowded.",
    lastDoneText: "Last done 33 days ago",
    doneCount: 1,
    pinned: false,
  },
];
